name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build Release x64
      run: |
        $version = "${{ github.ref_name }}" -replace '^v', ''
        msbuild src/ARCC.sln /p:Configuration=Release /p:Platform=x64 "/p:Version=$version" "/p:FileVersion=$version"
      shell: pwsh
    
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ARCC-${{ github.ref_name }}
        path: src/x64/Release/ARCC.exe
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## ARCC Release ${{ github.ref_name }}
          
          ### Changes
          - Automated release build
          
          Built from commit: ${{ github.sha }}
        files: |
          src/x64/Release/ARCC.exe
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}